#!/usr/bin/env bash
# Commit + push the R_GROUNDED_CLAIMS / benchmark / gate-hardening work.
# Stages ONLY the feature + fixes — generated/runtime files are left alone.
# Generated by the AXON session 2026-05-27. Safe to delete after use.
set -euo pipefail

REPO=/home/arturcastiel/projects/new-axon/axon
BRANCH=feat/grounded-claims-and-benchmark
cd "$REPO"

# Fresh branch (reuse if you re-run: delete the old one first)
if git rev-parse --verify "$BRANCH" >/dev/null 2>&1; then
  echo "Branch $BRANCH already exists — checking it out."
  git checkout "$BRANCH"
else
  git checkout -b "$BRANCH"
fi

# Stage exactly the feature + fixes (NOT workspace/AXON-DOCS.md, REGISTRY.json,
# cron.json, workspace/memory/, or the my-axon symlink — those are generated/runtime).
git add \
  benchmark/ .gitignore axon/KERNEL-SLIM.md \
  tools/rules/r_grounded_claims.py tools/rules/registry.py tools/verify.py \
  tools/dual_agent_eval.py tools/lint_paths.py tools/doc_anchors.py \
  tools/synapse_infer.py tools/neuron_audit.py tools/lint_commit_trailer.py \
  tools/crucible.json tools/freshness.py tools/docgen.py \
  tests/test_rules/test_r_grounded_claims.py tests/test_dual_agent_eval.py \
  tests/test_axon_audit_synapse.py tests/test_deprecation_log.py \
  tests/test_tools_kernel.py tests/test_neuron_audit.py \
  tests/test_lint_commit_trailer.py tests/test_freshness.py \
  tests/test_docgen_cwd_independent.py

echo "── staged files ──"
git diff --cached --name-only
echo "──────────────────"

# Commit — message is gate-clean (AXON trailer; no brand/footer/PR-N).
git commit -F - <<'MSG'
feat: R_GROUNDED_CLAIMS anti-fabrication gate + benchmark/ + hermetic crucible gate

R_GROUNDED_CLAIMS opt-in cite-or-abstain rule (+ kernel doc + tests); benchmark/
folder with 5 real goals and a live-only runner; crucible gate made hermetic
(tracked-only lint_paths, doc_anchors drops my-axon, 5 control cmds fixed,
neuron_audit --all, lint_commit_trailer --head); three bug fixes (synapse_infer
relative-path crash, freshness footer-timestamp false staleness, docgen cwd
dependence corrupting AXON-DOCS).

Co-authored-by: AXON <axon@arturcastiel.github.io>
MSG

# Push the branch.
git push -u origin "$BRANCH"

echo
echo "✓ committed + pushed $BRANCH"
echo "  main is force-push-protected → open a PR to merge."
echo "  (local merge if your policy allows:"
echo "     git checkout main && git merge --no-ff $BRANCH && git push origin main )"
